name       : plasma-integration
version    : 5.23.5
release    : 82
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/plasma-integration-5.23.5.tar.xz : 8f9672da0501e835763254e24b36069ba3bcd6c5ba90505fdfb7b1923766800d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
