name       : plasma-integration
version    : 5.23.1
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.1/plasma-integration-5.23.1.tar.xz : ca2b3487de16646bc5d2120adfd9d58cee69570a0eb64630ea075a93cdddcb71
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
