name       : plasma-integration
version    : 5.24.4
release    : 85
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.4/plasma-integration-5.24.4.tar.xz : 73d4993d2c7aeabbb068e8d28821566d04f2dcb882dd1d92feadc2062b3b4db4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
