name       : plasma-integration
version    : 5.10.3
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.3/plasma-integration-5.10.3.tar.xz : b6387a7fab2224307d63dad3bc0dedb12e17443ce79c02f383263389f7e7efee
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
