name       : plasma-integration
version    : 5.10.5
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.10.5/plasma-integration-5.10.5.tar.xz : 56c2adf52399536278dbad3605c1088e214ef6c57c72e06f297da2739be69d95
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - extra-cmake-modules
    - font-hack-ttf
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - noto-sans-ttf
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
