name       : plasma-integration
version    : 5.11.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.2/plasma-integration-5.11.2.tar.xz : 5444c3bf88bcf50f98ff4352cae4c4e323174ea8aa8f0f5c04bca54973ad7297
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - extra-cmake-modules
    - font-hack-ttf
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - noto-sans-ttf
rundeps    :
    - qqc2-desktop-style
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
