name       : plasma-integration
version    : 5.23.4
release    : 81
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.4/plasma-integration-5.23.4.tar.xz : 63780f6a20bbe23c33a7332a6ac7319ccbdb9ec4e906b4d4dbaf03d2acdb992c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
