name       : plasma-integration
version    : 5.12.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/plasma-integration-5.12.0.tar.xz : 1d78c5de77c7884b43ffac25f9a34aa4dbc3edeeac971c54be2fbac969bbad9a
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - extra-cmake-modules
    - font-hack-ttf
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - noto-sans-ttf
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
