name       : plasma-integration
version    : 5.11.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/plasma-integration-5.11.1.tar.xz : 9e9662d8d89f98fae1a5682e831abf068a564d720cd8bbd8e99ececb6884fa4a
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - extra-cmake-modules
    - font-hack-ttf
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - noto-sans-ttf
rundeps    :
    - qqc2-desktop-style
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
