name       : plasma-integration
version    : 5.22.5
release    : 76
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/plasma-integration-5.22.5.tar.xz : 28c743f1a911042dac1dd86ae615748b7b5422e8d4b47bff34d31cf4bdb6f270
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
setup      : |
    %apply_patches
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
