name       : plasma-integration
version    : 5.17.5
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/plasma-integration-5.17.5.tar.xz : 169206bebd790d2fee49cec621c46f6f64a8e20ee3e56bf16ee7373f61cad959
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcursor)
    - breeze-devel
    - extra-cmake-modules
    - font-hack-ttf
    - kconfigwidgets-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwayland-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - noto-sans-ttf
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
setup      : |
    patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
